# Generated by Django 5.0.6 on 2024-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eactive',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
